<?php

namespace BookingBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class BookingRepository extends EntityRepository
{
    public function nbTicket()
    {
        /**
         * Nombre de ticket restant par rapport à la dernière commande
         */

        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('BookingBundle:Booking', 'a')
            ->where('a.dateVisite = \'2016-11-16\'')
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
